spring:
  debug: true
  logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    initialization-mode: always
  flyway:
    baseline-on-migrate: true
  mustache:
    expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebook.client-id}
            client-secret: ${facebook.client-secret}
        provider:
          facebook:
            user-name-attribute: email
server:
  port: 8443
  ssl:
    key-alias: "cakefactory"
    key-store: "classpath:cakefactory.p12"
    key-store-password: "changeit"