spring:
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
datasource:
    url: jdbc:postgresql://localhost:5432/database/public
    username: postgres
    password: postgres
    initialization-mode: always